### ISSUE TITLE
Upgrade league/csv dependecy

### ISSUE THREAD

**Issue by milanjandric** [barrelstrength/craft-sprout-base#11]
Is it possible to update a league/csv to a newer version?  "^9"
There are more and more plugins that require the newest version. 

Thank you.

**Comment by BenParizek** [comment]
We'll look into getting this updated a coming release.

**Comment by pdaleramirez** [comment]
I have updated the league/csv to have v9 and i tested the new version library on sprout reports and as well as sprout email both plugins use the feature and all works fine.

**Comment by BenParizek** [comment]
@milanjandric We've reverted to support league/csv v8.2 as v9 requires a higher version of PHP than Craft does. It seems several other plugin developers have run into this issue as well, so we'll be holding out on upgrading until the PHP version is in line with Craft defaults or the general consensus among other plugin devs using the package is to move to v9.

I'd consider reaching out to any plugins using v9 and ask them to consider using v8.2 if they can and if that's not an option we should probably get folks starting to petition Craft to support a slightly higher version of PHP to encourage us all to upgrade to the latest versions of these packages.
