### ISSUE TITLE
Dependency conflicw with NSM Fields

### ISSUE THREAD

**Issue by brandonkelly** [barrelstrength/craft-sprout-base#8]
There is a dependency conflict between this package (so all Sprout plugins) and [NSM Fields](https://github.com/newism/craft3-fields):

- `barrelstrength/sprout-base` requires `commerceguys/addressing@^0.8.4`
- `newism/craft3-fields` requires `commerceguys/addressing@^1.0.1`

Since Sprout is the one that is behind, I think this is the one that should get updated to match NSM Fields.

**Comment by pdaleramirez** [comment]
@BenParizek This is the branch https://github.com/barrelstrength/craft-sprout-base/commits/feature/upgrade-adderss-v1 
for the v1 commerceguys/address sprout-fields support. This will also auto support sprout-seo address

**Comment by BenParizek** [comment]
Resolved in https://github.com/barrelstrength/craft-sprout-fields/blob/v3/CHANGELOG.md#3120---2018-11-14
